[build]
builder = "DOCKERFILE"
dockerfilePath = "Dockerfile"

[deploy]
healthcheckPath = "/ping"
healthcheckTimeout = 10
healthcheckInterval = 30
restartPolicyType = "ON_FAILURE"
restartPolicyMaxRetries = 3

[environments.production.variables]
NODE_ENV = "production"
DB_HOST = "metro.proxy.rlwy.net"
DB_USER = "root"
DB_PASSWORD = "LzFhsYXmMSAmyFYeIlUOZabkUBQyJEEs"
DB_NAME = "railway"
DB_PORT = "45542"
JWT_SECRET = "seu-segredo-super-secreto"
