[providers]
nodejs = "20.x"

[build]
cmds = [
    "npm ci --only=production --no-fund --no-audit --ignore-scripts",
    "npm cache clean --force"
]

[start]
cmd = "npm start"

[variables]
NODE_ENV = "production"
NPM_CONFIG_FUND = "false"
NPM_CONFIG_AUDIT = "false"
NPM_CONFIG_UPDATE_NOTIFIER = "false"
