[providers]
nodejs = "18.x"

[build]
cmds = [
    "npm install --production --no-package-lock --no-fund --no-audit",
    "npm rebuild canvas || true"
]

[start]
cmd = "npm start"

[variables]
NODE_ENV = "production"
NPM_CONFIG_FUND = "false"
NPM_CONFIG_AUDIT = "false"
