[providers]
nodejs = "20.x"

[build]
cmds = [
    "npm cache clean --force",
    "rm -rf node_modules package-lock.json",
    "npm install --force --verbose --no-fund --no-audit",
    "npm list express || npm install express@^4.19.2 --force",
    "ls -la node_modules/ | grep express || echo 'Express verification failed'"
]

[start]
cmd = "chmod +x railway-deploy.sh && ./railway-deploy.sh"

[variables]
NODE_ENV = "production"
NPM_CONFIG_FUND = "false"
NPM_CONFIG_AUDIT = "false"
NPM_CONFIG_UPDATE_NOTIFIER = "false"
