[build]
builder = "NIXPACKS"

[deploy]
startCommand = "chmod +x railway-deploy.sh && ./railway-deploy.sh"
# Healthcheck desabilitado temporariamente para debugging
# healthcheckPath = "/health"
healthcheckTimeout = 600
healthcheckInterval = 60
restartPolicyType = "ON_FAILURE"
restartPolicyMaxRetries = 5

[environments.production.variables]
NODE_ENV = "production"
NPM_CONFIG_FUND = "false"
NPM_CONFIG_AUDIT = "false"
NPM_CONFIG_UPDATE_NOTIFIER = "false"
DISABLE_HEALTHCHECK = "true"

[build.env]
NODE_ENV = "production"
FORCE_INSTALL = "true"
