[build]
builder = "NIXPACKS"

[deploy]
startCommand = "chmod +x emergency-deploy.sh && ./emergency-deploy.sh"
healthcheckPath = "/health"
healthcheckTimeout = 300
healthcheckInterval = 30
restartPolicyType = "ON_FAILURE"
restartPolicyMaxRetries = 5

[environments.production.variables]
NODE_ENV = "production"
NPM_CONFIG_FUND = "false"
NPM_CONFIG_AUDIT = "false"
NPM_CONFIG_UPDATE_NOTIFIER = "false"

[build.env]
NODE_ENV = "production"
FORCE_INSTALL = "true"
